name: Rail
options:
  bundleIdPrefix: com.rail
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

targets:
  Rail:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Rail
        excludes:
          - "**/.DS_Store"
    info:
      path: Rail/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        UISupportedInterfaceOrientations~iphone:
          - UIInterfaceOrientationPortrait
        CFBundleDisplayName: Rail
        NSSupportsLiveActivities: true
        UIBackgroundModes:
          - fetch
          - remote-notification
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rail.app
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_CFBundleDisplayName: Rail
        INFOPLIST_KEY_NSSupportsLiveActivities: YES
        INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
        INFOPLIST_KEY_UIBackgroundModes: "fetch remote-notification"
        SUPPORTS_MACCATALYST: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    entitlements:
      path: Rail/Rail.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.rail.app
    dependencies:
      - target: RailWidgetExtension
        embed: true

  RailWidgetExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: RailWidget
        excludes:
          - "**/.DS_Store"
    info:
      path: RailWidget/Info.plist
      properties:
        CFBundleDisplayName: Rail Widget
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rail.app.widget
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    entitlements:
      path: RailWidget/RailWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.rail.app

schemes:
  Rail:
    build:
      targets:
        Rail: all
        RailWidgetExtension: all
    run:
      config: Debug
      simulateLocation: false
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
